# Generated by Django 3.2.9 on 2023-01-19 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BaykarApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airvehicle',
            name='iff_code',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='airvehicle',
            name='weight',
            field=models.FloatField(),
        ),
    ]
