# Generated by Django 3.2.9 on 2023-01-19 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BaykarApp', '0003_remove_airvehicle_updated_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='airvehicle',
            name='created_date',
        ),
    ]
